name: user_registration
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1


environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  gap: ^3.0.1
  convex_bottom_bar: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  table_calendar: ^3.0.0

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/images/


  fonts:
    - family: Rowdies
      fonts:
        - asset: assets/fonts/Rowdies-Light.ttf

